name: rwAllStars
favicon: null
layout_spectrum: 0.10701
typography_spectrum: 0.73423
title: Real Estate by All Stars
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#aaa9a7'
    - '#af0007'
    - '#646464'
  brandStrength: 0.8358053741976619
  lightness: 0.6945333343464881
  saturation: 0.1795097019057721
  rhythmicContrast: 0.2774541834369302
purpose: []
